title:  İsa ALP
tagline:  
author:
  name: "isa alp"
  twitter:  #

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: '#'}
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
